from selenium.webdriver.common.by import By


class Locators:
    button_add_element = (By.XPATH, "//button[@onclick='addElement()']")
    button_delete_element = (By.XPATH, "//button[@onclick='deleteElement()']")
    congratulations_text = (By.XPATH, "//*[@class='example']")
    checkbox = (By.XPATH, "//input[@type='checkbox']")
    context_menu = (By.XPATH, "//*[@id='hot-spot']")
    dropdown = (By.XPATH, "//*[@id='dropdown']")
    gallery = (By.XPATH, "//a[normalize-space()='Gallery']")
    element = (By.XPATH, "//div[@id='column-a']")
    destination = (By.XPATH, "//div[@id='column-b']")
    checkbox_dinamic = (By.XPATH, "//input[@type='checkbox']")
    button_remove = (By.XPATH, "//button[normalize-space()='Remove']")
    text_luck = (By.XPATH, "//p[@id='message']")
    button_add = (By.XPATH, "//button[normalize-space()='Add']")
    button_enable = (By.XPATH, "//button[normalize-space()='Enable']")
    input_dis = (By.XPATH, "//input[@type='text']")
    button_start = (By.XPATH, "//button[normalize-space()='Start']")
    text_hello = (By.XPATH, "//h4[normalize-space()='Hello World!']")
    modal_window = (By.XPATH, "// h3[normalize - space() = 'This is a modal window']")
    file_upload = (By.XPATH, "//input[@id='file-upload']")
    button_upload = (By.XPATH, "//input[@id='file-submit']")
    message_file_upload = (By.XPATH, "//h3[normalize-space()='File Uploaded!']")
    part_menu = (By.XPATH, "//a[normalize-space()='Contact']")
    slider = (By.XPATH, "//input[@type='range']")
    number_slider = (By.XPATH, "//div[@class='example']//div[1]//img[1]")
    image_one = (By.XPATH, "//div[@class='example']//div[1]//div[1]//a[1]")
    input_input = (By.XPATH, "//input[@type='number']")
    key_main = (By.XPATH, "//p[@id='result']")
    alert_js = (By.XPATH, "//button[normalize-space()='Click for JS Alert']")
    alert_confirm = (By.XPATH, "//button[normalize-space()='Click for JS Confirm']")
    alert_prompt = (By.XPATH, "//button[normalize-space()='Click for JS Prompt']")
